// Localized UI strings. Add more language codes as needed.
// Fallback is always "en".

const UI_STRINGS = {
  en: {
    choose:     "⚔️ CHOOSE A TOPIC TO DEFEND",
    attacks:    "🗣️ COMMON ATTACKS — TAP TO RESPOND",
    askOwn:     "Ask your own question",
    placeholder:"e.g. Someone said Catholics worship idols...",
    chatPh:     "Type an attack or question...",
    consulting: "Consulting Scripture & Tradition...",
    emptyMsg:   "Ask any challenge to the faith and get a scholarly, Biblical response.",
    verse:      '"Always be ready to give an explanation to anyone who asks you for a reason for your hope." — 1 Pet 3:15',
    fresh:      "Start fresh",
    scripture:  "More Scripture",
    early:      "Early Church answer?",
    simple:     "Explain simply",
    langTitle:  "Choose Your Language",
    phSection:  "🇵🇭 MGA WIKANG PILIPINO · PHILIPPINE LANGUAGES",
    intlSection:"🌐 OTHER LANGUAGES",
    subtitle:   "FAITH DEFENSE GUIDE",
    home:       "← Home",
  },
  fil: {
    choose:     "⚔️ PUMILI NG PAKSA",
    attacks:    "🗣️ MGA KARANIWANG ATAKE",
    askOwn:     "Magtanong ng sarili mo",
    placeholder:"Hal. Sinabi ng isang tao na...",
    chatPh:     "I-type ang atake o tanong...",
    consulting: "Kumukonsulta sa Kasulatan at Tradisyon...",
    emptyMsg:   "Magtanong tungkol sa pananampalataya at makatanggap ng sagot mula sa Kasulatan.",
    verse:      '"Laging maging handa sa pagbibigay ng sagot sa sinumang nagtatanong sa inyo." — 1 Ped 3:15',
    fresh:      "Magsimula ulit",
    scripture:  "Dagdag na Kasulatan",
    early:      "Sinaunang Simbahan?",
    simple:     "Ipaliwanag nang simple",
    langTitle:  "Pumili ng Wika",
    phSection:  "🇵🇭 MGA WIKANG PILIPINO",
    intlSection:"🌐 IBANG MGA WIKA",
    subtitle:   "GABAY SA PAGTATANGGOL NG PANANAMPALATAYA",
    home:       "← Home",
  },
  ceb: {
    choose:     "⚔️ PILIA ANG HILISGUTAN",
    attacks:    "🗣️ MGA KOMON NGA ATAKE",
    askOwn:     "Pangutana sa imong kaugalingon",
    placeholder:"Hal. Giingon sa usa ka tawo nga...",
    chatPh:     "I-type ang atake o pangutana...",
    consulting: "Nagkonsulta sa Kasulatan ug Tradisyon...",
    emptyMsg:   "Mangutana bahin sa pagtuo ug makadawat og tubag gikan sa Kasulatan.",
    verse:      '"Kanunay nga mag-andam sa paghatag og tubag sa bisan kinsa." — 1 Ped 3:15',
    fresh:      "Sugdi pag-usab",
    scripture:  "Dugang Kasulatan",
    early:      "Tubag sa Unang Simbahan?",
    simple:     "Ipasabot og yano",
    langTitle:  "Pilia ang Pinulongan",
    phSection:  "🇵🇭 MGA PINULONGANG PILIPINO",
    intlSection:"🌐 UBAN PANG MGA PINULONGAN",
    subtitle:   "GIYA SA PAGPANALIPOD SA PAGTUO",
    home:       "← Home",
  },
  ilo: {
    choose:     "⚔️ PILIEN TI PAKSA",
    attacks:    "🗣️ KADAWYAN A PANAGBABAWI",
    askOwn:     "Mangalay ti bukodmo a saludsod",
    placeholder:"Halimbawa: Kinuna ti maysa a tao nga...",
    chatPh:     "I-type ti panagbabawi wenno saludsod...",
    consulting: "Agkonsulta iti Nasantuan a Sursurat...",
    emptyMsg:   "Mangalay maipapan iti pammati ken matanggap ti sungbat manipud iti Sursurat.",
    verse:      '"Listo kayo a dagus nga mangisungbat iti aniaman a mangisaludsod kadakayo." — 1 Ped 3:15',
    fresh:      "Rugi manen",
    scripture:  "Ad-adu a Sursurat",
    early:      "Napalabas a Simbaan?",
    simple:     "Ipaliwanag nga simple",
    langTitle:  "Pilien ti Pagsasao",
    phSection:  "🇵🇭 PAGSASAO TI PILIPINAS",
    intlSection:"🌐 SABALI A PAGSASAO",
    subtitle:   "GIYA PARA ITI PANANGIDEPENSA TI PAMMATI",
    home:       "← Home",
  },
  hil: {
    choose:     "⚔️ PILIA ANG TOPIKO",
    attacks:    "🗣️ MGA ORDINARYO NGA ATAKE",
    askOwn:     "Pangutana ang imo mismo",
    placeholder:"Hal. Ginsiling sang isa ka tawo nga...",
    chatPh:     "I-type ang atake ukon pangutana...",
    consulting: "Nagakonsulta sa Kasulatan kag Tradisyon...",
    emptyMsg:   "Mangutana parte sa pagtoo kag makabaton sang sabat halin sa Kasulatan.",
    verse:      '"Pirme mag-andam sa paghatag sang sabat sa bisan sin-o." — 1 Ped 3:15',
    fresh:      "Magsugod liwat",
    scripture:  "Dugang Kasulatan",
    early:      "Sabat sang Unang Simbahan?",
    simple:     "Ipaathag sing yano",
    langTitle:  "Pilia ang Yinaknan",
    phSection:  "🇵🇭 MGA YINAKNAN SA PILIPINAS",
    intlSection:"🌐 IBA NGA MGA YINAKNAN",
    subtitle:   "GIYA SA PAGDEPENSA SANG PAGTOO",
    home:       "← Home",
  },
}

export const getUI = (code) => UI_STRINGS[code] || UI_STRINGS['en']
